# Generated by Django 5.1.4 on 2025-01-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
